#' Access a workspace group
#'
#' @description
#' Provides access to a workspace group.
#'
#'
#' @param login [Login-class] Login object generated by either [login_studio()].
#' @param wsg_id Numeric. Workspace group id (see URL).
#' @param wsg_label Character. Workspace label.
#' @param ws_ids Numeric (optional). IDs of the workspaces the object should have access to. Defaults to all available workspaces of the workspace group (not recommended to leave as is).
#' @param ws_labels Character  (optional). Labels of the workspaces the object should have access to. Defaults to all available workspaces of the workspace group (not recommended to leave as is).
#' @param verbose Logical. If `TRUE`, additional information is printed. Defaults to `FALSE`.
#'
#' @return [WorkspaceGroup-class] object.
#'
#' @aliases
#' access_workspace_group,LoginStudio-method
#'
#' @export
setGeneric("access_workspace_group",
           function(login,
                    wsg_id = NULL, wsg_label = NULL,
                    ws_ids = NULL, ws_labels = NULL,
                    verbose = FALSE) {
             cli_setting()

             if (is.null(wsg_label) && is.null(wsg_id)) {
               cli::cli_abort("Either workspace {.wsg-label wsg_label} or
                              {.wsg-id ws_id} must be defined.", wrap = TRUE)
             }

             if (!is.null(wsg_label)) {
               wsg_labels <-
                 login@wsg_list %>%
                 purrr::map("wsg_label") %>%
                 unlist()

               if (!wsg_label %in% wsg_labels) {
                 cli::cli_abort("Provided {.wsg-label wsg_label} ({.wsg-label {wsg_label}})
                 does not match any {.wsg-label wsg_label} of a workspace you have access to.
                 Please check.", wrap = TRUE)
               } else {
                 check_wsg_id <-
                   login@wsg_list %>%
                   purrr::keep(function(wsg) wsg$wsg_label == wsg_label) %>%
                   purrr::list_flatten() %>%
                   purrr::pluck("wsg_id")

                 if (is.null(wsg_id)) {
                   wsg_id <- check_wsg_id
                 }
               }
             }

             if (!is.null(wsg_id)) {
               wsg_ids <-
                 login@wsg_list %>%
                 purrr::map("wsg_id") %>%
                 unlist()

               if (!wsg_id %in% wsg_ids) {
                 cli::cli_abort("Provided {.wsg-id wsg_id} ({.wsg-id {wsg_id}})
                 does not match any {.wsg-id wsg_id} of a workspace you have access to.
                 Please check.", wrap = TRUE)
               } else {
                 check_wsg_label <-
                   login@wsg_list %>%
                   purrr::keep(function(wsg) wsg$wsg_id == wsg_id) %>%
                   purrr::list_flatten() %>%
                   purrr::pluck("wsg_label")

                 if (is.null(wsg_label)) {
                   wsg_label <- check_wsg_label
                 }
               }
             }

             if (exists("check_wsg_id") && check_wsg_id != wsg_id) {
               cli::cli_abort("The {.wsg-id wsg_id} ({.wsg-id {check_wsg_id}}) of the provided
                 {.wsg-label wsg_label} ({.wsg-label {wsg_label}}) does not match the provided
                 {.wsg-id wsg_id} ({.wsg-id {wsg_id}}). Please check or select either
                 ({.wsg-id wsg_id}) or ({.wsg-label wsg_label})",
                              wrap = TRUE)
             }

             if (exists("check_wsg_label") && check_wsg_label != wsg_label) {
               cli::cli_abort("The {.wsg-label wsg_label} ({.wsg-label {check_wsg_label}}) of the provided
                 {.wsg-id wsg_id} ({.wsg-id {wsg_id}}) does not match the provided
                 {.wsg-label wsg_label} ({.wsg-label {wsg_label}}). Please check or select either
                 ({.wsg-id wsg_id}) or ({.wsg-label wsg_label})",
                              wrap = TRUE)
             }

             standardGeneric("access_workspace_group")
           })

#' @describeIn access_workspace_group Provide access to a selected workspace group after logging in
setMethod("access_workspace_group",
          signature = signature(login = "LoginStudio"),
          function(login, wsg_id, wsg_label = NULL, ws_ids = NULL, ws_labels = NULL, verbose) {
            # TODO: rewrite this
            wsg_meta <-
              login@wsg_list %>%
              purrr::map(function(wsg) {
                wsg$ws_list %>%
                  purrr::map(function(ws) {
                    ws$wsg_id <- wsg$wsg_id
                    ws$wsg_label <- wsg$wsg_label

                    ws
                  })
              }) %>%
              purrr::list_flatten() %>%
              purrr::keep(function(ws) {
                ws$wsg_id == wsg_id
              })

            if (!is.null(ws_ids)) {
              wsg_meta <-
                wsg_meta %>%
                purrr::keep(function(ws) {
                  ws$ws_id %in% ws_ids
                })
            }

            # WorkspaceGroup <- new("WorkspaceStudio",
            #                       login = login,
            #                       ws_id = as.numeric(ws_meta$ws_id),
            #                       ws_label = as.character(ws_meta$ws_label),
            #                       wsg_id = as.numeric(ws_meta$wsg_id),
            #                       wsg_label = as.character(ws_meta$wsg_label)
            # )

            ws_list <-
              purrr::map(
                wsg_meta,
                function(ws) {
                  access_workspace(login, ws_id = ws$ws_id, verbose = verbose)
                }
              )

            WorkspaceGroup <- new("WorkspaceGroupStudio",
                                  login = login,
                                  wsg_id = as.numeric(wsg_id),
                                  wsg_label = as.character(wsg_label),
                                  ws_list = ws_list)

            cli::cli_alert_success("IQB Studio workspace group successfully accessed.")

            if (verbose) {
              show(WorkspaceGroup)
            }

            return(WorkspaceGroup)
          })

