#' Access a workspace
#'
#' @description
#' Provides access to a workspace.
#'
#'
#' @param login [Login-class] Login object generated by either [login_studio()] or [login_testcenter()].
#' @param ws_id Numeric. Workspace ws_id (see URL).
#' @param ws_label Character. Workspace ws_label.
#' @param verbose Logical. If `TRUE`, additional information is printed. Defaults to `FALSE`.
#'
#' @return [Workspace-class] object.
#'
#' @aliases
#' access_workspace,LoginTestcenter-method,LoginStudio-method
#'
#' @export
setGeneric("access_workspace",
           function(login, ws_id = NULL, ws_label = NULL, verbose = FALSE) {
             cli_setting()

             if (is.null(ws_label) && is.null(ws_id)) {
               cli::cli_abort("Either workspace {.ws-label ws_label} or
                              {.ws-id ws_id} must be defined.", wrap = TRUE)
             }

             if (!is.null(ws_label)) {
               ws_labels <-
                 login@ws_list %>%
                 purrr::map("ws_label") %>%
                 unlist()

               if (!ws_label %in% ws_labels) {
                 cli::cli_abort("Provided {.ws-label ws_label} ({.ws-label {ws_label}})
                 does not match any {.ws-label ws_label} of a workspace you have access to.
                 Please check.", wrap = TRUE)
               } else {
                 check_ws_id <-
                   login@ws_list %>%
                   purrr::keep(function(ws) ws$ws_label == ws_label) %>%
                   purrr::list_flatten() %>%
                   purrr::pluck("ws_id")

                 if (is.null(ws_id)) {
                   ws_id <- check_ws_id
                 }
               }
             }

             if (!is.null(ws_id)) {
               ws_ids <-
                 login@ws_list %>%
                 purrr::map("ws_id") %>%
                 unlist()

               if (!ws_id %in% ws_ids) {
                 cli::cli_abort("Provided {.ws-id ws_id} ({.ws-id {ws_id}})
                 does not match any {.ws-id ws_id} of a workspace you have access to.
                 Please check.", wrap = TRUE)
               } else {
                 check_ws_label <-
                   login@ws_list %>%
                   purrr::keep(function(ws) ws$ws_id == ws_id) %>%
                   purrr::list_flatten() %>%
                   purrr::pluck("ws_label")

                 if (is.null(ws_label)) {
                   ws_label <- check_ws_label
                 }
               }
             }

             if (exists("check_ws_id") && check_ws_id != ws_id) {
               cli::cli_abort("The {.ws-id ws_id} ({.ws-id {check_ws_id}}) of the provided
                 {.ws-label ws_label} ({.ws-label {ws_label}}) does not match the provided
                 {.ws-id ws_id} ({.ws-id {ws_id}}). Please check or select either
                 ({.ws-id ws_id}) or ({.ws-label ws_label})",
                              wrap = TRUE)
             }

             if (exists("check_ws_label") && check_ws_label != ws_label) {
               cli::cli_abort("The {.ws-label ws_label} ({.ws-label {check_ws_label}}) of the provided
                 {.ws-id ws_id} ({.ws-id {ws_id}}) does not match the provided
                 {.ws-label ws_label} ({.ws-label {ws_label}}). Please check or select either
                 ({.ws-id ws_id}) or ({.ws-label ws_label})",
                              wrap = TRUE)
             }

             standardGeneric("access_workspace")
           })

#' @describeIn access_workspace Provide access to a selected workspace after logging in
setMethod("access_workspace",
          signature = signature(login = "LoginStudio"),
          function(login, ws_id, ws_label, verbose) {
            ws_meta <-
              login@wsg_list %>%
              purrr::map(function(wsg) {
                wsg$ws_list %>%
                  purrr::map(function(ws) {
                    ws$wsg_id <- wsg$wsg_id
                    ws$wsg_label <- wsg$wsg_label

                    ws
                  })
              }) %>%
              purrr::list_flatten() %>%
              purrr::keep(function(ws) {
                ws$ws_id == ws_id
              }) %>%
              purrr::list_flatten()

            Workspace <- new("WorkspaceStudio",
                             login = login,
                             ws_id = as.numeric(ws_meta$ws_id),
                             ws_label = as.character(ws_meta$ws_label),
                             wsg_id = as.numeric(ws_meta$wsg_id),
                             wsg_label = as.character(ws_meta$wsg_label)
            )

            cli::cli_alert_success("IQB Studio workspace successfully accessed.")

            if (verbose) {
              show(Workspace)
            }

            return(Workspace)
          })


#' @describeIn access_workspace Provide access to a selected workspace after logging in
#'
#' @param ws_id Numeric. Workspace ws_id (see URL).
#' @param ws_label Character. Workspace ws_label.
setMethod("access_workspace",
          signature = signature(login = "LoginTestcenter"),
          function(login, ws_id, ws_label, verbose) {

            ws_meta <-
              login@ws_list %>%
              purrr::keep(function(ws) {
                ws$ws_id == ws_id
              }) %>%
              purrr::list_flatten()

            Workspace <- new("WorkspaceTestcenter",
                             login = login,
                             ws_id = as.numeric(ws_meta$ws_id),
                             ws_label = as.character(ws_meta$ws_label))

            cli::cli_alert_success("IQB Testcenter workspace successfully accessed.")

            if (verbose) {
              show(Workspace)
            }

            return(Workspace)
          })

