#' Add metadata to units
#'
#' @param units Tibble holding units retrieved from [get_units()].
#'
#' @description
#' This function adds the unit metadata for a unit table generated by calling [get_units()].
#'
#' @return A tibble.
#' @export
add_metadata <- function(units) {
  ws_settings <- attr(units, "ws_settings")
  items_profile <- ws_settings %>% dplyr::select(ws_id, "item_metadata") %>% tidyr::unnest(item_metadata)
  unit_profile <- ws_settings %>% dplyr::select(ws_id, "unit_metadata") %>% tidyr::unnest(unit_metadata)

  if (tibble::has_name(units, "unit_metadata")) {
    units <- read_metadata(units = units)
  }

  unit_start <-
    units %>%
    dplyr::select(
      -c(unit_profiles, items_profiles)
    ) %>%
    tidyr::unnest(
      items_list
    ) %>%
    dplyr::mutate(
      unit_has_items = is.na(item_no)
    ) %>%
    # TODO: Remove this in 2026 (all relevant units should have updated metdata profiles)
    dplyr::rowwise() %>%
    dplyr::mutate(
      unit_has_uuids = dplyr::if_any(dplyr::any_of("item_uuid"), ~ !is.na(.), .default = FALSE)
    ) %>%
    {
      if ("item_uuid" %in% names(.)) {
        dplyr::mutate(., unit_has_uuids = !is.na(item_uuid))
      } else {
        dplyr::mutate(., unit_has_uuids = FALSE)
      }
    } %>%
    dplyr::ungroup()

  items_meta <-
    units %>%
    dplyr::select(ws_id, unit_id, items_profiles) %>%
    tidyr::unnest(items_profiles, keep_empty = TRUE) %>%
    add_profile(id = c("unit_id", "item_no"), profile = items_profile, check = item_has_profile)

  unit_meta <-
    units %>%
    dplyr::select(ws_id, unit_id, unit_profiles) %>%
    tidyr::unnest(unit_profiles, keep_empty = TRUE) %>%
    add_profile(id = "unit_id", profile = unit_profile, check = unit_has_profile) %>%
    # Fix for SFB; TODO: should be adjusted for more flexibility
    dplyr::rename(dplyr::any_of(c(
      "Konstruktbereich" = "Konstrukt"
    )))

  unit_start %>%
    dplyr::left_join(unit_meta, by = dplyr::join_by("ws_id", "unit_id")) %>%
    # TODO: Better switch to item_uuid?
    dplyr::left_join(items_meta, by = dplyr::join_by("ws_id", "unit_id", "item_no"))
}


# Adds profiles to all columns if possible
add_profile <- function(metadata, id, profile, check) {
  profile_multiples <-
    profile %>%
    dplyr::filter(multiple) %>%
    dplyr::pull(profile_name)

  profile_vocabularies <-
    profile %>%
    dplyr::filter(profile_type == "vocabulary") %>%
    dplyr::pull(profile_name)

  profile_names <-
    profile %>%
    dplyr::pull(profile_name)

  if (tibble::has_name(metadata, "profile_name")) {
    metadata %>%
      dplyr::mutate(
        value = ifelse(is.na(value_id), value_text, value_id)
      ) %>%
      dplyr::select(
        ws_id, dplyr::all_of(id), profile_name, value
      ) %>%
      tidyr::pivot_wider(
        names_from = profile_name,
        values_from = value,
        values_fn = list
      ) %>%
      tidyr::unnest(!tidyr::any_of(profile_multiples)) %>%
      dplyr::select(ws_id, dplyr::all_of(id), dplyr::any_of(profile_names)) %>%
      dplyr::mutate(
        dplyr::across(everything(), function(x) {
          col_name <- dplyr::cur_column()

          if (col_name %in% profile_vocabularies) {
            recode_profile <-
              profile %>%
              dplyr::filter(profile_name == col_name) %>%
              purrr::pluck("data", 1)

            if (col_name %in% profile_multiples) {
              purrr::map(x, function(x) {
                factor(x, levels = recode_profile$value_id, labels = recode_profile$value_label) %>%
                  as.character()
              })
            } else {
              factor(x, levels = recode_profile$value_id, labels = recode_profile$value_label) %>%
                as.character()
            }
          }
          else {
            x
          }
        })
      ) %>%
      dplyr::rowwise() %>%
      dplyr::mutate(
        {{ check }} := any(!is.na(dplyr::c_across(dplyr::any_of(profile_names))))
      ) %>%
      dplyr::ungroup()
  } else {
    metadata %>%
      dplyr::select(unit_id) %>%
      dplyr::mutate(
        {{ check }} := FALSE
      )
  }
}
