#' Get multiple units with resources
#'
#' @param workspace [WorkspaceStudio-class]. Workspace information necessary to retrieve the unit and item metadata from the API.
#' @param units Tibble holding units retrieved from get units.
#'
#' @description
#' This function adds the unit metadata for a unit table generated by repeatedly [get_unit()] or [get_units()].
#'
#' @return A tibble.
#' @export
#'
#' @aliases
#' add_metadata,WorkspaceStudio-method
setGeneric("add_metadata", function(workspace, units) {
  cli_setting()

  standardGeneric("add_metadata")
})

#' @describeIn add_metadata Get multiple unit information and coding schemes in a defined workspace
setMethod("add_metadata",
          signature = signature(workspace = "WorkspaceStudio"),
          function(workspace, units) {
            ws_settings <- get_settings(workspace, metadata = TRUE)
            items_profile <- ws_settings %>% purrr::pluck("item_metadata", 1)
            unit_profile <- ws_settings %>% purrr::pluck("unit_metadata", 1)

            unit_start <-
              units %>%
              dplyr::select(
                -c(unit_profiles, items_profiles)
              ) %>%
              # dplyr::mutate(
              #   items_meta = purrr::map(items_meta,
              #                           function(x) x %>% dplyr::mutate(item = as.character(item)))
              # ) %>%
              tidyr::unnest(
                items_meta
              )

            items_meta <-
              units %>%
              dplyr::select(unit_id, items_profiles) %>%
              tidyr::unnest(items_profiles) %>%
              add_profile(c(unit_id, item_no), profile = items_profile)

            unit_meta <-
              units %>%
              dplyr::select(unit_id, unit_profiles) %>%
              tidyr::unnest(unit_profiles) %>%
              add_profile(unit_id, profile = unit_profile)

            # ws_info <-
            #   ws_settings %>%
            #   dplyr::select(
            #     ws_id, ws_name, ws_groupId, ws_groupName
            #   )

            unit_start %>%
              # dplyr::bind_cols(ws_info) %>%
              dplyr::left_join(unit_meta) %>%
              dplyr::left_join(items_meta)
          })


# Adds profiles to all columns if possible
add_profile <- function(metadata, id, profile) {
  profile_multiples <-
    profile %>%
    dplyr::filter(multiple) %>%
    dplyr::pull(profile_name)

  profile_vocabularies <-
    profile %>%
    dplyr::filter(profile_type == "vocabulary") %>%
    dplyr::pull(profile_name)

  metadata %>%
    dplyr::mutate(
      value = ifelse(is.na(value_id), value_text, value_id)
    ) %>%
    dplyr::select(
      {{ id }}, profile_name, value
    ) %>%
    tidyr::pivot_wider(
      names_from = profile_name,
      values_from = value,
      values_fn = list
    ) %>%
    tidyr::unnest(!tidyr::any_of(profile_multiples)) %>%
    dplyr::mutate(
      dplyr::across(everything(), function(x) {
        col_name <- dplyr::cur_column()

        if (col_name %in% profile_vocabularies) {
          recode_profile <-
            profile %>%
            dplyr::filter(profile_name == col_name) %>%
            purrr::pluck("data", 1)

          if (col_name %in% profile_multiples) {
            purrr::map(x, function(x) factor(x, levels = recode_profile$value_id, labels = recode_profile$value_label))
          } else {
            factor(x, levels = recode_profile$value_id, labels = recode_profile$value_label)
          }
        }
        else {
          x
        }
      })
    )
}
