#' Adds prepared coding scheme to units
#'
#' @param units Tibble holding units retrieved from [get_units()].
#' @param filter_has_codes Only returns variables that were not deactivated. Defaults to `TRUE`.
#'
#' @description
#' This function adds the coding schemes for a unit table generated by calling [get_units()]. Please note that this replaces the column `coding_scheme` from the retrieved units, which is therefore no longer a valid option for [code_responses()].
#'
#' @return A tibble.
#' @export
add_coding_scheme <- function(units, filter_has_codes = TRUE) {
  cli_setting()

  unit_keys <- units$unit_key

  if (!tibble::has_name(units, "coding_scheme")) {
    cli::cli_abort("No column {.field coding_scheme} in {.unit-key units}.")
  }

  if (length(unit_keys) > 0) {
    units %>%
      dplyr::select(
        ws_id,
        ws_label,
        unit_id,
        unit_key,
        unit_label,
        schemer,
        scheme_type,
        coding_scheme
      ) %>%
      dplyr::mutate(
        coding_scheme = purrr::map(coding_scheme, function(coding_scheme) {
          prepare_coding_scheme(coding_scheme, filter_has_codes = filter_has_codes)
        },
        .progress = list(
          type ="custom",
          extra = list(
            unit_keys = unit_keys
          ),
          format = "Preparing coding scheme for {.unit-key {cli::pb_extra$unit_keys[cli::pb_current+1]}} ({cli::pb_current}/{cli::pb_total}): {cli::pb_bar} {cli::pb_percent} | ETA: {cli::pb_eta}",
          format_done = "Prepared {cli::pb_total} coding scheme{?s} in {cli::pb_elapsed}.",
          clear = FALSE
        ))
      ) %>%
      tidyr::unnest(coding_scheme)
  } else {
    units
  }
}
